name: Build and publish

on:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          poetry build

      - name: Publish
        run: |
          poetry config "pypi-token.pypi" ${{ secrets.PYPI_API_TOKEN }}
          poetry publish